### ISSUE TITLE
Compiler Error C2280 “attempting to reference a deleted function” bwidgets/screen_graph/Iterators

### ISSUE THREAD

**Issue by lihaochen910** [julianeisel/bWidgets#8]
Windows 10, VS2019

bwidgets/screen_graph/Iterators.h
bwidgets/screen_graph/Iterators.cc

demo\screen\DefaultStage.cc(135,1):error C2280: “bWidgets::bwScreenGraph::PreOrderIterator::PreOrderIterator(const bWidgets::bwScreenGraph::PreOrderIterator &)”

demo\screen\Stage.cc(159,1):error C2280: “bWidgets::bwScreenGraph::PreOrderIterator::PreOrderIterator(const bWidgets::bwScreenGraph::PreOrderIterator &)”

**Comment by julianeisel** [comment]
Finally got around to looking into a whole bunch of Windows issues, so this should finally be fixed with 0115ad5906edaf.
Sorry for taking so long to check on this, I actually couldn't recreate on my previous setup.
